language: python
python:
  - "3.8"

install: "pip install -r requirements.txt"

dist: bionic

addons:
  apt:
    packages:
      - imagemagick
      - libjpeg-progs
      - optipng

script:
  - make publish

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
  after_success:
    - bash invalidateCloudflareCache.sh
