language: python
python:
  - "3.5"

install: "pip install -r requirements.txt"

dist: trusty

addons:
  apt:
    packages:
      - imagemagick
      - libjpeg-progs

script:
  - bash build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: deploy
  on:
    branch: master
