.. _conferences-label:

Timeline
--------

* 2019
    * DPG-Frühjahrstagung (Spring Meeting), Regensburg
        * `Ground-state energy distribution of noninteracting fermions with a random energy spectrum`, :download:`download slides <pdf/2019DPG.pdf>`
* 2018
    * XXX IUPAP Conference on Computational Physics, Davis, CA
        * `Large Deviations of Convex Hulls of Self-Avoiding Random Walks`, :download:`download slides <pdf/2018CCP.pdf>`
    * DPG-Frühjahrstagung (Spring Meeting), Berlin
        * `Linear Programming and Cutting Planes for Ground States and Excited States of the Traveling Salesperson Problem`, :download:`download slides <pdf/2018DPG.pdf>`
* 2017
    * CompPhys17, 18th International NTZ-Workshop on New Developments in Computational Physics, Leipzig
        * `Linear Programming and Cutting Planes for Ground States and Excited States of the Traveling Salesperson Problem`, :download:`download slides <pdf/2017CompPhys.pdf>`
    * `Fundamental Problems in Statistical Physics XIV` (FPSP XIV), Bruneck
    * DPG-Frühjahrstagung (Spring Meeting), Dresden
        * `Convex Hulls of Random Walks in High Dimensions: A Large-Deviation Study`, `show slides <https://dpg2017.schawe.me/>`_
        * `Convex Hulls of Self-Avoiding Random Walks: A Large-Deviation Study`, :download:`download poster <pdf/2017DPG.pdf>`
* 2016
    * CompPhys16, 17th International NTZ-Workshop on New Developments in Computational Physics, Leipzig
        * `Convex Hulls of Self-Avoiding Random Walks: A Large-Deviation Study`, :download:`download poster <pdf/2016CompPhys.pdf>`
    * Visit to the *Laboratoire de Physique Théorique et Modèles Statistiques* (LPTMS) (Orsay, France)
    * DPG-Frühjahrstagung (Spring Meeting), Regensburg
        * `Phase Transitions of Disordered Travelling Salesperson Problems solved with Linear Programming and Cutting Planes`, :download:`download slides <pdf/2016DPG.pdf>`
    * Master of Science in Physics, Carl von Ossietzky University Oldenburg, :download:`thesis <pdf/masterThesis.pdf>`
* 2015
    * `Bad Honnef Physics School: Computational Physics of Complex and Disordered Systems`, Bad Honnef, :download:`download poster <pdf/2015MCS.pdf>`
* 2014
    * `5th International Summer School on Modern Compuational Science Compuational Quantum Chemistry`, Oldenburg
    * DPG-Frühjahrstagung (Spring Meeting), Dresden
        * `Ising-Ferromagnet on Proximity Graphs`, :download:`download poster <pdf/2014DPG.pdf>`
* 2013
    * Bachelor of Science in Physics, Carl von Ossietzky University Oldenburg, :download:`thesis <pdf/bachelorThesis.pdf>`
