.. _conferences-label:

Timeline
--------

* 2017
    * `Fundamental Problems in Statistical Physics XIV` (FPSP XIV), Bruneck
    * DPG-Frühjahrstagung (Spring Meeting), Dresden
        * `Convex Hulls of Random Walks in High Dimensions: A Large-Deviation Study`, `show slides <https://dpg2017.schawe.me/>`_
        * `Convex Hulls of Self-Avoiding Random Walks: A Large-Deviation Study`, :download:`download poster <pdf/2017DPG.pdf>`
* 2016
    * CompPhys16, Leipzig
        * `Convex Hulls of Self-Avoiding Random Walks: A Large-Deviation Study`, :download:`download poster <pdf/2016CompPhys.pdf>`
    * Visit to the *Laboratoire de Physique Théorique et Modèles Statistiques* (LPTMS) (Orsay, France)
    * DPG-Frühjahrstagung (Spring Meeting), Regensburg
        * `Phase Transitions of Disordered Travelling Salesperson Problems solved with Linear Programming and Cutting Planes`, :download:`download slides <pdf/2016DPG.pdf>`
    * Master of Science in Physics, CvO University Oldenburg, :download:`download <pdf/masterThesis.pdf>`
* 2015
    * `Bad Honnef Physics School: Computational Physics of Complex and Disordered Systems`, Bad Honnef, :download:`download poster <pdf/2015MCS.pdf>`
* 2014
    * `5th International Summer School on Modern Compuational Science Compuational Quantum Chemistry`, Oldenburg
    * DPG-Frühjahrstagung (Spring Meeting), Dresden
        * `Ising-Ferromagnet on Proximity Graphs`, :download:`download poster <pdf/2014DPG.pdf>`
* 2013
    * Bachelor of Science in Physics, CvO University Oldenburg, :download:`download <pdf/bachelorThesis.pdf>`
