from datetime import date

EVENTS = [
    {
        "date": date(2013, 9, 5),
        "country": "DE",
        "place": "Carl von Ossietzky Universität Oldenburg",
        "name": "Bachelor of Science",
        "type": "graduation",
        "presentations": ["2013gradBSC"],
    },
    {
        "date": date(2014, 8, 25),
        "date_end": date(2014, 9, 5),
        "country": "DE",
        "place": "Oldenburg",
        "name": "5th International Summer School on Modern Compuational Science: Compuational Quantum Chemistry",
        "link": "https://www.mcs.uni-oldenburg.de/64155.html",
        "type": "summerschool",
    },
    {
        "date": date(2014, 3, 30),
        "date_end": date(2014, 4, 4),
        "country": "DE",
        "place": "Dresden",
        "name": "DPG-Frühjahrstagung",
        "link": "https://dresden14.dpg-tagungen.de/",
        "type": "conference",
        "presentations": ["2014confDPG"],
    },
    {
        "date": date(2015, 9, 20),
        "date_end": date(2015, 9, 25),
        "country": "DE",
        "place": "Bad Honnef",
        "name": "Bad Honnef Physics School: Computational Physics of Complex and Disordered Systems",
        "link": "https://www.dpg-physik.de/veranstaltungen/2015/bad-honnef-physics-school-computational-physics-of-complex-and-disordered-systems",
        "type": "summerschool",
        "presentations": ["2015sschoolMCS"],
    },
    {
        "date": date(2015, 11, 6),
        "country": "DE",
        "place": "Carl von Ossietzky Universität Oldenburg",
        "name": "Master of Science",
        "type": "graduation",
        "presentations": ["2015gradMSC"],
    },
    {
        "date": date(2016, 3, 1),
        "date_end": date(2019, 8, 31),
        "country": "DE",
        "place": "Carl von Ossietzky Universität Oldenburg",
        "name": "Institut für Physik (IfP), AG Compphys",
        "title": "wissenschaftlicher Mitarbeiter",
        "type": "work",
    },
    {
        "date": date(2016, 3, 6),
        "date_end": date(2016, 3, 11),
        "country": "DE",
        "place": "Regensburg",
        "name": "DPG-Frühjahrstagung",
        "link": "https://regensburg16.dpg-tagungen.de/",
        "type": "conference",
        "presentations": ["2016confDPG"],
    },
    {
        "date": date(2016, 9, 1),
        "date_end": date(2016, 9, 30),
        "country": "FR",
        "place": "Université Paris-Sud, Orsay",
        "name": "Laboratoire de Physique Théorique et Modèles Statistiques (LPTMS)",
        "title": "research visitor",
        "type": "visit",
    },
    {
        "date": date(2016, 11, 24),
        "date_end": date(2016, 11, 26),
        "country": "DE",
        "place": "Leipzig",
        "name": "CompPhys16, 17th International NTZ-Workshop on New Developments in Computational Physics",
        "link": "https://www.physik.uni-leipzig.de/~janke/CompPhys16/",
        "type": "workshop",
        "presentations": ["2016CompPhys"],
    },
    {
        "date": date(2017, 3, 19),
        "date_end": date(2017, 3, 24),
        "country": "DE",
        "place": "Dresden",
        "name": "DPG-Frühjahrstagung",
        "link": "https://dresden17.dpg-tagungen.de/",
        "type": "conference",
        "presentations": [
            "2017confDPG_saw",
            "2017confDPG_high"
        ]
    },
    {
        "date": date(2017, 7, 16),
        "date_end": date(2017, 7, 29),
        "country": "IT",
        "place": "Bruneck",
        "name": "Fundamental Problems in Statistical Physics XIV",
        "link": "https://fpspxiv.sciencesconf.org/",
        "type": "summerschool",
    },
    {
        "date": date(2017, 11, 30),
        "date_end": date(2017, 12, 2),
        "country": "DE",
        "place": "Leipzig",
        "name": "CompPhys17, 18th International NTZ-Workshop on New Developments in Computational Physics",
        "link": "https://www.physik.uni-leipzig.de/~janke/CompPhys17/",
        "type": "workshop",
        "presentations": ["2017confCompPhys"],
    },
    {
        "date": date(2018, 3, 11),
        "date_end": date(2018, 3, 16),
        "country": "DE",
        "place": "Berlin",
        "name": "DPG-Frühjahrstagung",
        "link": "https://berlin18.dpg-tagungen.de/",
        "type": "conference",
        "presentations": ["2018confDPG"],
    },
    {
        "date": date(2018, 7, 29),
        "date_end": date(2018, 8, 2),
        "country": "US",
        "place": "Davis, CA",
        "name": "XXX IUPAP Conference on Computational Physics",
        "link": "http://ccp2018.physics.ucdavis.edu",
        "type": "conference",
        "presentations": ["2018confCCP"],
    },
    {
        "date": date(2019, 3, 31),
        "date_end": date(2019, 4, 5),
        "country": "DE",
        "place": "Regensburg",
        "name": "DPG-Frühjahrstagung",
        "link": "https://regensburg19.dpg-tagungen.de/",
        "type": "conference",
        "presentations": ["2019confDPG"],
    },
    {
        "date": date(2019, 3, 19),
        "country": "DE",
        "place": "Carl von Ossietzky Universität Oldenburg",
        "name": "Doktor der Naturwissenschaften (Dr. rer. nat.)",
        "type": "graduation",
        "presentations": [
            "2019gradPHD_thesis",
            "2019gradPHD_defense"
        ],
    },
    {
        "date": date(2019, 9, 1),
        "date_end": date(2020, 8, 31),
        "country": "FR",
        "place": "CY Cergy Paris Université",
        "name": "Laboratoire de Physique Théorique et Modélisation (LPTM)",
        "title": "Postdoc",
        "type": "work",
    },
    {
        "date": date(2020, 3, 15),
        "date_end": date(2020, 3, 20),
        "country": "DE",
        "place": "Dresden",
        "name": "DPG-Frühjahrstagung (cancelled)",
        "link": "https://dresden20.dpg-tagungen.de/",
        "type": "conference",
        "presentations": [
            "2020confDPG_hk",
            "2020confDPG_lis"
        ],
    },
    {
        "date": date(2020, 7, 9),
        "date_end": date(2020, 7, 10),
        "country": "FR",
        "place": "Cergy",
        "name": "Theoretical and Mathematical Physics in Cergy Paris, Singapore, and Warwick (remote)",
        "link": "https://iea.u-cergy.fr/en/scientific-events/conferences-and-workshops/theoretical-and-mathematical-physics.html",
        "type": "workshop",
        "presentations": [
            "2020confIC2S2_video",
            "2020confIC2S2_poster",
        ],
    },
    {
        "date": date(2020, 7, 17),
        "date_end": date(2020, 7, 20),
        "country": "US",
        "place": "Cambridge, MA",
        "name": "International Conference on Computational Social Science (remote)",
        "link": "http://2020.ic2s2.org/",
        "type": "conference",
        "presentations": [
            "2020confIC2S2_video",
            "2020confIC2S2_poster",
        ],
    },
]

import pycountry
for i in EVENTS:
    if "country" in i:
        i["country"] = pycountry.countries.get(alpha_2=i["country"]).name
