[build]
  command = "git submodule update --init --recursive --depth=1 && pip install -q uv && uv sync && uv run make publish"
  publish = "output"
  branch = "master"

[context.branch-deploy]
  command = "echo"
  publish = "."