[build]
  command = "git submodule update --init --recursive --depth=1 && pip install -q poetry && poetry export --dev --without-hashes > requirements.txt && pip install -r requirements.txt && make publish"
  publish = "output"
  branch = "master"

[context.branch-deploy]
  command = "echo"
  publish = "."