PUBLICATIONS = [
    {
        "doi": "10.1209/0295-5075/113/30004",
        "arxiv": "1512.08554",
        "pdf": "2016_TSP_EPL.pdf",
        "comment": "direct link is fine: point (2) in https://authors.epletters.net/documents/copyright.pdf 'all or part [..] including the authors' personal home page'",
        "related": ["2015sschoolMCS", "2015gradMSC", "2016confDPG"],
    },
    {
        "doi": "10.1038/s41598-017-08531-8",
        "pdf": "2017_IFM_SciRep.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
        "related": ["2013gradBSC", "2014confDPG"],
    },
    {
        "doi": "10.1103/PhysRevE.96.062101",
        "arxiv": "1709.02638",
        "pdf": "2017_convex_highdim_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
        "related": ["2017confDPG_high"],
    },
    {
        "doi": "10.1103/PhysRevE.97.062159",
        "arxiv": "1804.02371",
        "pdf": "2018_convex_avoiding_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
        "related": ["2016CompPhys", "2017confDPG_saw"],
    },
    {
        "doi": "10.1209/0295-5075/124/40005",
        "arxiv": "1808.09246",
        "pdf": "2018_srn_EPL.pdf",
        "comment": "direct link is fine: point (2) in https://authors.epletters.net/documents/copyright.pdf 'all or part [..] including the authors' personal home page'",
        "related": ["2019confDPG"],
    },
    {
        "doi": "10.1103/PhysRevE.99.042104",
        "arxiv": "1901.05235",
        "pdf": "2019_lis_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1140/epjb/e2019-90667-y",
        "arxiv": "1811.04816",
        "pdf": "2019_bi_EPJB_accepted.pdf",
        "comment": "direct link is forbidden: is explicitly not allowed 'He/she may not use the publisher’s version (the final article), which is posted on SpringerLink and other Springer websites, for the purpose of self-archiving or deposit.' instead I use the explicitly allowed accepted version 'Authors may self-archive the Author’s accepted manuscript of their articles on their own websites.' but we can share the view link https://rdcu.be/bumov",
    },
    {
        "doi": "10.1371/journal.pone.0215309",
        "arxiv": "1702.02821",
        "pdf": "2019_sat_PLOSONE.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
    },
    {
        "doi": "10.1103/PhysRevE.100.032135",
        "arxiv": "1806.08681",
        "pdf": "2019_tsprsb_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
        "related": ["2017confCompPhys", "2018confDPG"],
    },
    {
        "doi": "10.1088/1742-6596/1290/1/012029",
        "arxiv": "1808.10698",
        "pdf": "2019_convex_true_JOPCS.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
        "related": ["2018confCCP"],
    },
    {
        "doi": "10.1103/PhysRevE.101.032102",
        "arxiv": "1907.00486",
        "pdf": "2020_lis2_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1038/s41598-020-64691-0",
        "arxiv": "2001.06877",
        "pdf": "2020_hk_SciRep.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
        "related": ["2020confDPG_hk", "2020confR4", "2020confIC2S2_poster", "2020confIC2S2_video"],
        "supplementary": ["2020supp1SciRep_hk", "2020supp2SciRep_hk"],
    },
    {
        "doi": "10.1088/1742-5468/ab7c5f",
        "arxiv": "1912.08778",
        "pdf": "2020_rtp_JSTAT_accepted.pdf",
        "alphabetical": True,
        "comment": "the published version is explicitly forbidden, but the accepted manuscript is explicitly allowed without embargo (https://publishingsupport.iopscience.iop.org/questions/quick-check-guide-current-author-rights-policy/)",
    },
    {
        "doi": "10.1103/PhysRevE.101.062109",
        "arxiv": "2003.12847",
        "pdf": "2020_liscount_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
        "related": ["2020confDPG_lis"],
    },
    {
        "doi": "10.1038/s41598-020-70809-1",
        "arxiv": "2007.00432",
        "pdf": "2020_hkcost_SciRep.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
        "related": ["2020confCSW_video"],
    },
    {
        "doi": "10.1103/PhysRevE.102.052108",
        "arxiv": "2003.03415",
        "pdf": "2020_sbm_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1103/PhysRevE.102.062141",
        "arxiv": "2010.00325",
        "pdf": "2020_scent_PRE.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1103/PhysRevE.103.012130",
        "arxiv": "2009.01487",
        "pdf": "2021_tele_PRE.pdf",
        "alphabetical": True,
        "bonus": "Editors' Suggestion",
        "related": ["2021confSMR3624_talk"],
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1103/PhysRevE.103.022135",
        "arxiv": "2011.06668",
        "pdf": "2021_rbm_PRE.pdf",
        "alphabetical": True,
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1103/PhysRevResearch.3.023208",
        "arxiv": "2102.10910",
        "pdf": "2021_hknet_PRR.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
        "related": ["2021suppHKdata", "2021suppDWdata"],
        "supplementary": ["2021suppPRR_hknet_lat3", "2021suppPRR_hknet_lat4", "2021suppPRR_hknet_ba10"],
    },
    {
        "doi": "10.1088/1751-8121/ac2dc2",
        "arxiv": "2110.04188",
        "pdf": "2021_zero_JPA.pdf",
        "alphabetical": True,
        "comment": "the published version is explicitly forbidden, but the accepted manuscript is explicitly allowed without embargo (https://publishingsupport.iopscience.iop.org/questions/quick-check-guide-current-author-rights-policy/)",
    },
    {
        "doi": "10.1038/s42005-022-00807-4",
        "arxiv": "2111.12165",
        "pdf": "2022_hyper_CommPhys.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
    },
    {
        "doi": "10.1088/1751-8121/ac62bb",
        "arxiv": "2112.08752",
        "pdf": "2022_rtpa_JPA.pdf",
        "comment": "the published version is explicitly forbidden, but the accepted manuscript is explicitly allowed without embargo (https://publishingsupport.iopscience.iop.org/questions/quick-check-guide-current-author-rights-policy/)",
    },
    {
        "doi": "10.1103/PhysRevB.107.064208",
        "arxiv": "2208.14955",
        #"pdf": "2023_lis_rsb_PRB.pdf",
        "comment": "direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement 'The right to use all or part of the Article, including the APS-prepared version without revision or modification, on the author(s)’ web home page [..]'",
    },
    {
        "doi": "10.1038/s41598-023-30367-8",
        "arxiv": "2208.14393",
        "pdf": "2023_tnyt_SciRep.pdf",
        "comment": "direct link is fine: Open Access (creative commons license)",
    },
]

PREPRINTS = [
    {
        "arxiv": "1803.08015",
        "pdf": "pp_bat.pdf",
    },
    {
        "arxiv": "2207.10488",
        "pdf": "pp_relax.pdf",
    },
    {
        "arxiv": "2301.09233",
        "pdf": "pp_hkhet.pdf",
    },
    {
        "arxiv": "2303.08535",
        "pdf": "pp_relaxbox.pdf",
    },
]
