.. _pub-label:

Publications
------------

1. Phase Transitions of Traveling Salesperson Problems solved with Linear Programming and Cutting Planes
    * Hendrik Schawe, Alexander K. Hartmann -- Europhysics Letters **113**, 30004 (2016)
    * `doi:10.1209/0295-5075/113/30004 <http://dx.doi.org/10.1209/0295-5075/113/30004>`_
    * `arXiv:1512.08554 [cond-mat.dis-nn] <https://arxiv.org/abs/1512.08554>`_
    * :download:`download article <pdf/2016_TSP_EPL.pdf>`

    .. direct link is fine: point (2) in https://authors.epletters.net/documents/copyright.pdf
    .. "all or part [..] including the authors' personal home page"

2. Ising Ferromagnets on Proximity Graphs with Varying Disorder of the Node Placement
    * Hendrik Schawe, Christoph Norrenbrock, Alexander K. Hartmann -- Scientific Reports **7**, 8040 (2017)
    * `doi:10.1038/s41598-017-08531-8 <http://dx.doi.org/10.1038/s41598-017-08531-8>`_
    * :download:`download article <pdf/2017_IFM_SciRep.pdf>`

    .. direct link is fine: Open Access (creative commons license)

3. Convex hulls of random walks in higher dimensions: A large deviation study
    * Hendrik Schawe, Alexander K. Hartmann, Satya N. Majumdar -- Physical Review E **96**, 062101 (2017)
    * `doi:10.1103/PhysRevE.96.062101 <http://dx.doi.org/10.1103/PhysRevE.96.062101>`_
    * `arXiv:1709.02638 [cond-mat.stat-mech] <https://arxiv.org/abs/1709.02638>`_
    * :download:`download article <pdf/2017_convex_highdim_PRE.pdf>`

    .. direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement

4. Large deviations of convex hulls of self-avoiding random walks
    * Hendrik Schawe, Alexander K. Hartmann, Satya N. Majumdar -- Physical Review E **97**, 062159 (2018)
    * `doi:10.1103/PhysRevE.97.062159 <http://dx.doi.org/10.1103/PhysRevE.97.062159>`_
    * `arXiv:1804.02371 [cond-mat.stat-mech] <https://arxiv.org/abs/1804.02371>`_
    * :download:`download article <pdf/2018_convex_avoiding_PRE.pdf>`

    .. direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement

5. Ground-state energy of noninteracting fermions with a random energy spectrum
    * Hendrik Schawe, Alexander K. Hartmann, Satya N. Majumdar, Grégory Schehr -- Europhysics Letters **124**, 40005 (2018)
    * `doi:10.1209/0295-5075/124/40005 <http://dx.doi.org/10.1209/0295-5075/124/40005>`_
    * `arXiv:1808.09246 [cond-mat.dis-nn] <https://arxiv.org/abs/1808.09246>`_
    * :download:`download article <pdf/2018_srn_EPL.pdf>`

    .. direct link is fine: point (2) in https://authors.epletters.net/documents/copyright.pdf
    .. "all or part [..] including the authors' personal home page"


Preprints
---------

6. Large-deviation properties of the largest biconnected component for random graphs
    * Hendrik Schawe, Alexander K. Hartmann
    * `arXiv:1811.04816 [cond-mat.dis-nn] <https://arxiv.org/abs/1811.04816>`_
    * :download:`download preprint <pdf/pp_bi.pdf>`

#. Large Deviations of Convex Hulls of the "True" Self-Avoiding Random Walk
    * Hendrik Schawe, Alexander K. Hartmann
    * `arXiv:1808.10698 [cond-mat.stat-mech] <https://arxiv.org/abs/1808.10698>`_
    * :download:`download preprint <pdf/pp_true.pdf>`

#. Vertebrate pollinators: phase transition in a time-dependent generalized traveling-salesperson problem
    * M. Jungsbluth, J. Thiele, Y. Winter, H. Schawe, A. K. Hartmann
    * `arXiv:1803.08015 [physics.bio-ph] <https://arxiv.org/abs/1803.08015>`_
    * :download:`download preprint <pdf/pp_bat.pdf>`

#. Phase Transitions of the Typical Algorithmic Complexity of the Random Satisfiability Problem Studied with Linear Programming
    * Hendrik Schawe, Roman Bleim, Alexander K. Hartmann
    * `arXiv:1702.02821 [cond-mat.dis-nn] <https://arxiv.org/abs/1702.02821>`_
    * :download:`download preprint <pdf/pp_sat.pdf>`

#. Replica Symmetry and Replica Symmetry Breaking for the Traveling Salesperson Problem
    * Hendrik Schawe, Jitesh Kumar Jha, Alexander K. Hartmann
    * `arXiv:1806.08681 [cond-mat.dis-nn] <https://arxiv.org/abs/1806.08681>`_
    * :download:`download preprint <pdf/pp_tsprsb.pdf>`
