.. _pub-label:

List of Publications
--------------------

1. Phase Transitions of Traveling Salesperson Problems solved with Linear Programming and Cutting Planes
    * Hendrik Schawe, Alexander K. Hartmann -- EPL **113**, 30004 (2016)
    * `doi:10.1209/0295-5075/113/30004 <http://dx.doi.org/10.1209/0295-5075/113/30004>`_
    * `arXiv:1512.08554 [cond-mat.dis-nn] <http://arxiv.org/abs/1512.08554>`_

2. Ising Ferromagnets on Proximity Graphs with Varying Disorder of the Node Placement
    * Hendrik Schawe, Christoph Norrenbrock, Alexander K. Hartmann -- Scientific Reports **7**, 8040 (2017)
    * `doi:10.1038/s41598-017-08531-8 <http://dx.doi.org/10.1038/s41598-017-08531-8>`_

.. 2. Phase Transitions of the Typical Algorithmic Complexity of the Random Satisfiability Problem Studied with Linear Programming
..     * Hendrik Schawe, Roman Bleim, Alexander K. Hartmann, (submitted)
..     * `arXiv:1702.02821 [cond-mat.dis-nn] <http://arxiv.org/abs/1702.02821>`_
