.. _pub-label:

List of Publications
--------------------

1. Phase Transitions of Traveling Salesperson Problems solved with Linear Programming and Cutting Planes
    * Hendrik Schawe, Alexander K. Hartmann -- EPL **113**, 30004 (2016)
    * `doi:10.1209/0295-5075/113/30004 <http://dx.doi.org/10.1209/0295-5075/113/30004>`_
    * `arXiv:1512.08554 [cond-mat.dis-nn] <https://arxiv.org/abs/1512.08554>`_
    * :download:`download pdf <pdf/2016_TSP_EPL.pdf>`
    .. direct link is fine: point (2) in https://authors.epletters.net/documents/copyright.pdf
    .. "all or part [..] including the authors' personal home page"

2. Ising Ferromagnets on Proximity Graphs with Varying Disorder of the Node Placement
    * Hendrik Schawe, Christoph Norrenbrock, Alexander K. Hartmann -- Scientific Reports **7**, 8040 (2017)
    * `doi:10.1038/s41598-017-08531-8 <http://dx.doi.org/10.1038/s41598-017-08531-8>`_
    * :download:`download pdf <pdf/2017_IFM_SciRep.pdf>`
    .. direct link is fine: Open Access (creative commons license)

3. Convex hulls of random walks in higher dimensions: A large deviation study
    * Hendrik Schawe, Alexander K. Hartmann, Satya N. Majumdar -- Physical Review E **96**, 062101 (2017)
    * `doi:10.1103/PhysRevE.96.062101 <https://link.aps.org/doi/10.1103/PhysRevE.96.062101>`_
    * `arXiv:1709.02638 [cond-mat.stat-mech] <https://arxiv.org/abs/1709.02638>`_
    * :download:`download pdf <pdf/2017_convex_highdim_PRE.pdf>`
    .. direct link is fine: point 3. in https://journals.aps.org/authors/transfer-of-copyright-agreement
