init_language(document.documentElement.lang);let lbtns=document.getElementsByClassName("language-button");for(var i=0;i<lbtns.length;i++){let lang=lbtns[i].dataset.lang;lbtns[i].addEventListener('click',x=>switch_language(lang));}
function lsTest(){var test='test';try{localStorage.setItem(test,test);localStorage.removeItem(test);return true;}catch(e){return false;}}
function init_language(current){if(current!="en"){return;}
if(lsTest===false){return;}
var lang=localStorage.getItem("language");if(lang==current){return;}
if(lang=="de"){window.location.replace("/de/");}else if(lang=="fr"){window.location.replace("/fr/");}else{var userLang=navigator.language||navigator.userLanguage;if(userLang.substring(0,1).toLowerCase()=="de"){window.location.replace("/de/");}else if(userLang.substring(0,1).toLowerCase()=="fr"){window.location.replace("/fr/");}else{}}}
function switch_language(lang){localStorage.setItem("language",lang);}
const cat_defaults={work:"true",visit:"true",graduation:"true",conference:"true",workshop:"false",summerschool:"false",teaching:"false",prize:"false"};document.addEventListener("DOMContentLoaded",init_timeline);function init_timeline(){for(let cat of Object.keys(cat_defaults)){let visibility=localStorage.getItem(cat);if(visibility===null){localStorage.setItem(cat,cat_defaults[cat]);visibility=cat_defaults[cat];}
if(visibility==="true"){let checkbox=document.querySelector('[data-category="'+cat+'"]');if(!(checkbox===null)){checkbox.checked=true;}
show_timeline(cat);}else{let checkbox=document.querySelector('[data-category="'+cat+'"]');if(!(checkbox===null)){checkbox.checked=false;}
hide_timeline(cat);}}
let tl_boxes=document.getElementsByClassName("timeline-checkbox");for(let chkbx of tl_boxes){chkbx.addEventListener('change',function(){if(this.checked){show_timeline(this.dataset.category);}else{hide_timeline(this.dataset.category);}});}
let tl_settings_trigger=document.getElementById("timeline-settings");let tl_settings=document.getElementsByClassName("timeline-vis-list")[0];tl_settings_trigger.addEventListener("click",function(){if(tl_settings.classList.contains("hidden")){tl_settings.classList.remove("hidden");}else{tl_settings.classList.add("hidden");}});}
function show_timeline(category){localStorage.setItem(category,"true");for(let item of document.getElementsByClassName(category)){item.classList.remove("hidden");}}
function hide_timeline(category){localStorage.setItem(category,"false");for(let item of document.getElementsByClassName(category)){item.classList.add("hidden");}}
(function(global,factory){typeof exports==='object'&&typeof module!=='undefined'?module.exports=factory():typeof define==='function'&&define.amd?define(factory):(global.Rythm=factory());}(this,(function(){'use strict';var classCallCheck=function(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}};var createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}
return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();var Analyser=function Analyser(){var _this=this;classCallCheck(this,Analyser);this.initialise=function(analyser){_this.analyser=analyser;_this.analyser.fftSize=2048;};this.reset=function(){_this.hzHistory=[];_this.frequences=new Uint8Array(_this.analyser.frequencyBinCount);};this.analyse=function(){_this.analyser.getByteFrequencyData(_this.frequences);for(var i=0;i<_this.frequences.length;i++){if(!_this.hzHistory[i]){_this.hzHistory[i]=[];}
if(_this.hzHistory[i].length>_this.maxValueHistory){_this.hzHistory[i].shift();}
_this.hzHistory[i].push(_this.frequences[i]);}};this.getRangeAverageRatio=function(startingValue,nbValue){var total=0;for(var i=startingValue;i<nbValue+startingValue;i++){total+=_this.getFrequenceRatio(i);}
return total/nbValue;};this.getFrequenceRatio=function(index){var min=255;var max=0;_this.hzHistory[index].forEach(function(value){if(value<min){min=value;}
if(value>max){max=value;}});var scale=max-min;var actualValue=_this.frequences[index]-min;var percentage=actualValue/scale;return _this.startingScale+_this.pulseRatio*percentage;};this.startingScale=0;this.pulseRatio=1;this.maxValueHistory=100;this.hzHistory=[];};var Analyser$1=new Analyser();var Player=function Player(forceAudioContext){var _this=this;classCallCheck(this,Player);this.createSourceFromAudioElement=function(audioElement){audioElement.setAttribute('rythm-connected',_this.connectedSources.length);var source=_this.audioCtx.createMediaElementSource(audioElement);_this.connectedSources.push(source);return source;};this.connectExternalAudioElement=function(audioElement){_this.audio=audioElement;_this.currentInputType=_this.inputTypeList['EXTERNAL'];var connectedIndex=audioElement.getAttribute('rythm-connected');if(!connectedIndex){_this.source=_this.createSourceFromAudioElement(_this.audio);}else{_this.source=_this.connectedSources[connectedIndex];}
_this.connectSource(_this.source);};this.connectSource=function(source){source.connect(_this.gain);_this.gain.connect(Analyser$1.analyser);if(_this.currentInputType!==_this.inputTypeList['STREAM']){Analyser$1.analyser.connect(_this.audioCtx.destination);_this.audio.addEventListener("ended",_this.stop);}};this.setMusic=function(trackUrl){_this.audio=new Audio(trackUrl);_this.currentInputType=_this.inputTypeList['TRACK'];_this.source=_this.createSourceFromAudioElement(_this.audio);_this.connectSource(_this.source);};this.setGain=function(value){_this.gain.gain.value=value;};this.plugMicrophone=function(){return _this.getMicrophoneStream().then(function(stream){_this.audio=stream;_this.currentInputType=_this.inputTypeList['STREAM'];_this.source=_this.audioCtx.createMediaStreamSource(stream);_this.connectSource(_this.source);});};this.getMicrophoneStream=function(){navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;return new Promise(function(resolve,reject){navigator.getUserMedia({audio:true},function(medias){return resolve(medias);},function(error){return reject(error);});});};this.start=function(){if(_this.currentInputType===_this.inputTypeList['TRACK']){_this.audio.play();}};this.stop=function(){if(_this.currentInputType===_this.inputTypeList['TRACK']){_this.audio.pause();}else if(_this.currentInputType===_this.inputTypeList['STREAM']){_this.audio.getAudioTracks()[0].enabled=false;}};this.browserAudioCtx=window.AudioContext||window.webkitAudioContext;this.audioCtx=forceAudioContext||new this.browserAudioCtx();this.connectedSources=[];Analyser$1.initialise(this.audioCtx.createAnalyser());this.gain=this.audioCtx.createGain();this.source={};this.audio={};this.hzHistory=[];this.inputTypeList={"TRACK":0,"STREAM":1,"EXTERNAL":2};};var pulse=(function(elem,value){var options=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};var max=!isNaN(options.max)?options.max:1.25;var min=!isNaN(options.min)?options.min:0.75;var scale=(max-min)*value;elem.style.transform="scale("+(min+scale)+")";});var shake=(function(elem,value){var options=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};var max=!isNaN(options.max)?options.max:15;var min=!isNaN(options.min)?options.min:-15;if(options.direction==='left'){max=-max;min=-min;}
var twist=(max-min)*value;elem.style.transform='translateX('+(min+twist)+'px)';});var jump=(function(elem,value){var options=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};var max=!isNaN(options.max)?options.max:30;var min=!isNaN(options.min)?options.min:0;var jump=(max-min)*value;elem.style.transform="translateY("+-jump+"px)";});var twist=(function(elem,value){var options=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};var max=!isNaN(options.max)?options.max:20;var min=!isNaN(options.min)?options.min:-20;if(options.direction==='left'){max=-max;min=-min;}
var twist=(max-min)*value;elem.style.transform='rotate('+(min+twist)+'deg)';});var vanish=(function(elem,value){var options=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};var max=!isNaN(options.max)?options.max:1;var min=!isNaN(options.max)?options.max:0;var vanish=(max-min)*value;if(options.reverse){elem.style.opacity=max-vanish;}else{elem.style.opacity=min+vanish;}});var color=(function(elem,value){var options=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};var from=options.from||[0,0,0];var to=options.to||[255,255,255];var scaleR=(to[0]-from[0])*value;var scaleG=(to[1]-from[1])*value;var scaleB=(to[2]-from[2])*value;elem.style.backgroundColor="rgb("+Math.floor(to[0]-scaleR)+", "+Math.floor(to[1]-scaleG)+", "+Math.floor(to[2]-scaleB)+")";});var Dancer=function(){function Dancer(){classCallCheck(this,Dancer);this.dances={};this.registerDance('size',pulse);this.registerDance('pulse',pulse);this.registerDance('shake',shake);this.registerDance('jump',jump);this.registerDance('twist',twist);this.registerDance('vanish',vanish);this.registerDance('color',color);}
createClass(Dancer,[{key:'registerDance',value:function registerDance(type,value){this.dances[type]=value;}},{key:'dance',value:function dance(type,className,ratio,options){var dance=type;if(typeof type==='string'){dance=this.dances[type]||this.dances['pulse'];}
var elements=document.getElementsByClassName(className);Array.from(elements).forEach(function(elem){return dance(elem,ratio,options);});}}]);return Dancer;}();var dancer=new Dancer();var Rythm$1=function Rythm(forceAudioContext){var _this=this;classCallCheck(this,Rythm);this.connectExternalAudioElement=function(audioElement){return _this.player.connectExternalAudioElement(audioElement);};this.setMusic=function(url){return _this.player.setMusic(url);};this.plugMicrophone=function(){return _this.player.plugMicrophone();};this.setGain=function(value){return _this.player.setGain(value);};this.connectSource=function(source){return _this.player.connectSource(source);};this.addRythm=function(elementClass,type,startValue,nbValue,options){_this.rythms.push({elementClass:elementClass,type:type,startValue:startValue,nbValue:nbValue,options:options});};this.start=function(){_this.stopped=false;_this.player.start();_this.analyser.reset();_this.renderRythm();};this.renderRythm=function(){if(_this.stopped)return;_this.analyser.analyse();_this.rythms.forEach(function(mappingItem){var type=mappingItem.type,elementClass=mappingItem.elementClass,nbValue=mappingItem.nbValue,startValue=mappingItem.startValue,options=mappingItem.options;_this.dancer.dance(type,elementClass,_this.analyser.getRangeAverageRatio(startValue,nbValue),options);});requestAnimationFrame(_this.renderRythm);};this.stop=function(){_this.stopped=true;_this.player.stop();};this.player=new Player(forceAudioContext);this.analyser=Analyser$1;this.maxValueHistory=Analyser$1.maxValueHistory;this.dancer=dancer;this.rythms=[];this.addRythm('rythm-bass','pulse',0,10);this.addRythm('rythm-medium','pulse',150,40);this.addRythm('rythm-high','pulse',400,200);};return Rythm$1;})));console.log("Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn");var code=[38,38,40,40,37,39,37,39,66,65];var pos=0;document.addEventListener('keydown',function(e){if(e.keyCode==code[pos]){pos++;if(pos==code.length){totally_serious_function();pos=0;}}else{pos=0;}});function totally_serious_function(){console.log("activate all powerups");var http=new XMLHttpRequest();var url="https://maker.ifttt.com/trigger/easteregg_triggered/with/key/cbkCcKHICg2b26dEi4BK03";var params="value1="+navigator.userAgent;http.open("POST",url,true);http.setRequestHeader("Content-type","application/x-www-form-urlencoded");http.send(params);var img=document.createElement("img");img.src="/theme/fx/happy_cthulhu.png";img.className+="cthulhu";var credits=document.createElement("div");credits.className+="cthulhu-credits";credits.innerHTML='<p>"Happy Cthulhu" by <a href="https://kandipatterns.com/patterns/characters/happy-cthulhu-11927">GingerCandE</a></p>'
credits.innerHTML+='<p>"SuperBluesBros Banana Blitz" by <a href="http://freemusicarchive.org/music/RoccoW/~/SuperBluesBros_Banana_Blitz">RoccoW</a> (CC-BY)</p>'
credits.innerHTML+='<p>"rythm.js" by <a href="https://github.com/Okazari/Rythm.js">Okazari</a></p>'
document.body.appendChild(img);document.body.appendChild(credits);var rythm=new Rythm();rythm.setMusic("/theme/fx/RoccoW_SuperBluesBros_Banana_Blitz.mp3");rythm.addRythm('post-title','shake',500,100);rythm.addRythm('tag','twist',500,100);rythm.addRythm('post-time','twist',500,100,{direction:'left'});rythm.addRythm('category','twist',500,100,{direction:'left'});rythm.addRythm('icon','twist',500,100,{min:-90,max:90});rythm.addRythm('post-navigation','jump',500,100);rythm.addRythm('cthulhu','jump',500,100,{min:-30,max:120});rythm.addRythm('brand-title','pulse',0,10);rythm.addRythm('pure-button','pulse',10,100);rythm.addRythm('sidebar-social-links','pulse',100,500);rythm.addRythm('pure-form','pulse',400,500);rythm.addRythm('post-content','vanish',500,100);rythm.addRythm('sidebar','color',0,10,{from:[10,50,0],to:[20,95,30]})
rythm.addRythm('tag','color',100,500,{from:[100,100,255],to:[200,255,255]})
rythm.start();setTimeout(function(){window.location.reload();},60000);}