name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install poetry
      run: pipx install poetry

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
        cache: 'poetry'
    - run: poetry install

    - name: build static sites
      run: DEBUG=1 poetry run make publish

    - name: GitHub Pages action
      if: github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
        force_orphan: true

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
            vulnerability-check: false
            base-ref: 3ed5b3b4
            head-ref: HEAD
            allow-licenses: Apache-2.0, PSF-2.0, MIT, MPL-2.0, LGPL-2.1, 0BSD, BSD-2-Clause, BSD-3-Clause, Python-2.0
            allow-dependencies-licenses: pkg:pypi/cssmin